#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop mqttvscpd.service >/dev/null || true
fi
# End automatically added section