# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/mqttvscpd-26.09.47.12-Linux-x64
Summary:        The VSCP daemon
Name:           mqttvscpd
Version:        26.09.47.12
Release:        1
License:        unknown
Group:          unknown
Vendor:         Ake Hedman,  contributors,, the VSCP project

Url: https://www.vscp.org


















%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename mqttvscpd-26.09.47.12-Linux-x64.rpm
%define _unpackaged_files_terminate_build 0





%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
%dir /etc/logrotate.d
%dir /etc/vscp
%dir /etc/vscp/certs
/etc/vscp/certs/README.md
/etc/vscp/certs/client.crt
/etc/vscp/certs/client.csr
/etc/vscp/certs/client.key
/etc/vscp/certs/client.pem
/etc/vscp/certs/client.pfx
/etc/vscp/certs/make_certs.bat
/etc/vscp/certs/make_certs.sh
/etc/vscp/certs/server.crt
/etc/vscp/certs/server.csr
/etc/vscp/certs/server.key
/etc/vscp/certs/server.pem
/etc/vscp/certs/server.pin
/etc/vscp/certs/server_bkup.crt
/etc/vscp/certs/server_bkup.csr
/etc/vscp/certs/server_bkup.key
/etc/vscp/certs/server_bkup.pem
/etc/vscp/certs/server_bkup.pin
/etc/vscp/certs/tcpip_client.crt
/etc/vscp/certs/tcpip_client.csr
/etc/vscp/certs/tcpip_client.key
/etc/vscp/certs/tcpip_client.pem
/etc/vscp/certs/tcpip_client.pfx
/etc/vscp/certs/tcpip_server.crt
/etc/vscp/certs/tcpip_server.csr
/etc/vscp/certs/tcpip_server.key
/etc/vscp/certs/tcpip_server.pem
/etc/vscp/certs/tcpip_server.pin
/usr/bin/download-event-db
/usr/bin/vscp_eth_to_guid
/usr/bin/vscp_ip_to_guid
%dir /usr/lib/systemd
%dir /usr/lib/systemd/system
/usr/lib/systemd/system/mqttvscpd.service
%dir /usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libvscp_client_base.so
/usr/lib/x86_64-linux-gnu/libvscp_client_canal.so
/usr/lib/x86_64-linux-gnu/libvscp_client_mqtt.so
/usr/lib/x86_64-linux-gnu/libvscp_client_multicast.so
/usr/lib/x86_64-linux-gnu/libvscp_client_socketcan.so
/usr/lib/x86_64-linux-gnu/libvscp_client_tcp.so
/usr/lib/x86_64-linux-gnu/libvscp_client_udp.so
/usr/lib/x86_64-linux-gnu/libvscp_client_ws1.so
/usr/lib/x86_64-linux-gnu/libvscp_client_ws2.so
/usr/lib/x86_64-linux-gnu/libvscp_common.so
/usr/lib/x86_64-linux-gnu/libvscp_core.so
/usr/lib/x86_64-linux-gnu/libvscp_guid.so
/usr/lib/x86_64-linux-gnu/libvscp_guidparser.so
/usr/lib/x86_64-linux-gnu/libvscp_mdf.so
/usr/lib/x86_64-linux-gnu/libvscp_sockettcp.so
/usr/lib/x86_64-linux-gnu/libvscp_util.so
%dir /usr/sbin
/usr/sbin/mqttvscpd
%dir /usr/share/doc/mqttvscpd
/usr/share/doc/mqttvscpd/LICENSE
/usr/share/doc/mqttvscpd/README.md
%dir /usr/share/man
%dir /usr/share/man/man8
/usr/share/man/man8/mqttvscpd.8*
%dir /usr/share/mqttvscp
/usr/share/mqttvscp/README-ca-certificates
/usr/share/mqttvscp/README-certs
%dir /usr/share/mqttvscp/systemd
/usr/share/mqttvscp/systemd/mqttvscpd.service.notify
/usr/share/mqttvscp/systemd/mqttvscpd.service.simple
%dir /var
%dir /var/lib
%dir /var/lib/vscp
%dir /var/lib/vscp/drivers
%dir /var/lib/vscp/drivers/level1
%dir /var/lib/vscp/drivers/level2
%dir /var/lib/vscp/mqttvscpd
/var/lib/vscp/mqttvscpd/vscp-hashtypeevents.sqlite3
/var/lib/vscp/mqttvscpd/vscp_events.sqlite3
%dir /var/lib/vscp/web
%dir /var/lib/vscp/web/html
%dir /var/lib/vscp/web/html/css
%dir /var/lib/vscp/web/html/images
%dir /var/lib/vscp/web/html/js
%dir /var/log
%dir /var/log/vscp

%config /etc/vscp/mqttvscpd.json
%config /etc/vscp/mqttvscpd.json.min-example
%config /etc/vscp/vscp.key
%config /var/lib/vscp/mqttvscpd/
%config /etc/vscp/certs/
%config /var/lib/vscp/drivers/level1/
%config /var/lib/vscp/drivers/level2/
%config /var/lib/vscp/web/html/css/
%config /var/lib/vscp/web/html/images/
%config /var/lib/vscp/web/html/js/
%config /var/log/vscp/
%config /etc/logrotate.d/mqttvscpd



%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 26.09.47.12-1
  Generated by CPack RPM (no Changelog file were provided)


