#ifndef MQTTVSCPD_VERSION_H
#define MQTTVSCPD_VERSION_H

#define MQTTVSCPD_VERSION_MAJOR 1
#define MQTTVSCPD_VERSION_MINOR 0
#define MQTTVSCPD_VERSION_PATCH 0

#define MQTTVSCPD_VERSION_STRING "1.0.0"
#define MQTTVSCPD_DISPLAY_VERSION "1.0.0"

#define MQTTVSCPD_COPYRIGHT \
	"Copyright (C) 2000-2026 Ake Hedman, the VSCP project, " \
	"https://www.vscp.org"

#endif // MQTTVSCPD_VERSION_H